// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using koncert.Models;

#nullable disable

namespace koncert.Migrations
{
    [DbContext(typeof(koncertDbContext))]
    [Migration("20240607233019_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("koncert.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("koncert.Models.Entities.Concert", b =>
                {
                    b.Property<int>("ConcertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConcertId"), 1L, 1);

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ConcertId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Concerts");
                });

            modelBuilder.Entity("koncert.Models.Entities.Description", b =>
                {
                    b.Property<int>("DescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescriptionId"), 1L, 1);

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DescriptionId");

                    b.HasIndex("ConcertId")
                        .IsUnique();

                    b.ToTable("Descriptions");
                });

            modelBuilder.Entity("koncert.Models.Entities.NoteOneDescription", b =>
                {
                    b.Property<int>("NoteOneDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteOneDescriptionId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DescriptionId")
                        .HasColumnType("int");

                    b.HasKey("NoteOneDescriptionId");

                    b.HasIndex("DescriptionId");

                    b.ToTable("NoteOneDescription");
                });

            modelBuilder.Entity("koncert.Models.Entities.NoteThreeOther", b =>
                {
                    b.Property<int>("NoteThreeOtherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteThreeOtherId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DescriptionId")
                        .HasColumnType("int");

                    b.HasKey("NoteThreeOtherId");

                    b.HasIndex("DescriptionId");

                    b.ToTable("NoteThreeOther");
                });

            modelBuilder.Entity("koncert.Models.Entities.NoteTwoSell", b =>
                {
                    b.Property<int>("NoteTwoSellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteTwoSellId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DescriptionId")
                        .HasColumnType("int");

                    b.HasKey("NoteTwoSellId");

                    b.HasIndex("DescriptionId");

                    b.ToTable("NoteTwoSell");
                });

            modelBuilder.Entity("koncert.Models.Entities.Concert", b =>
                {
                    b.HasOne("koncert.Models.Entities.Category", "Category")
                        .WithMany("Concerts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("koncert.Models.Entities.Description", b =>
                {
                    b.HasOne("koncert.Models.Entities.Concert", null)
                        .WithOne("Description")
                        .HasForeignKey("koncert.Models.Entities.Description", "ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("koncert.Models.Entities.NoteOneDescription", b =>
                {
                    b.HasOne("koncert.Models.Entities.Description", null)
                        .WithMany("NoteOneDescription")
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("koncert.Models.Entities.NoteThreeOther", b =>
                {
                    b.HasOne("koncert.Models.Entities.Description", null)
                        .WithMany("NoteThreeOther")
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("koncert.Models.Entities.NoteTwoSell", b =>
                {
                    b.HasOne("koncert.Models.Entities.Description", null)
                        .WithMany("NoteTwoSell")
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("koncert.Models.Entities.Category", b =>
                {
                    b.Navigation("Concerts");
                });

            modelBuilder.Entity("koncert.Models.Entities.Concert", b =>
                {
                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("koncert.Models.Entities.Description", b =>
                {
                    b.Navigation("NoteOneDescription");

                    b.Navigation("NoteThreeOther");

                    b.Navigation("NoteTwoSell");
                });
#pragma warning restore 612, 618
        }
    }
}
